name: lyvias-tale
version: '${version}'
main: cn.taskeren.lyviastale.LyviasTalePlugin
description: "Lyvia's Tale"
api-version: 1.18
author: Taskeren
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21" # Kotlin Standard Library
  - "org.litote.kmongo:kmongo:4.9.0" # KMongo, the Kotlin optimized Mongo client
depend:
  - "PlaceholderAPI"
permissions:
  lyviastale:
    description: "The root permission node of Lyvia's Tale"
    default: op
    children:
      lyviastale.command.cpop: true
      lyviastale.command.cv: true
      lyviastale.command.gcv: true
  lyviastale.command.cpop:
    description: "The permission to execute cpop command"
    default: op
  lyviastale.command.cv:
    description: "The permission to execute cv command"
    default: op
  lyviastale.command.gcv:
    description: "The permission to execute gcv command"
    default: op
commands:
  cpop:
    description: "Let the specific player to execute command as operator permission"
    usage: "/cpop <player> <...command args>"
    permission: lyviastale.command.cpop
  cv:
    description: ""
    usage: "/cv"
    permission: lyviastale.command.cv
  gcv:
    description: ""
    usage: "/gcv"
    permission: lyviastale.command.gcv